#!/bin/bash

scriptPath="$1"
filePrefix="$2"

echo "Processing Files for $filePrefix"
read -p "  Do you want to re-generate thumbnails for motions? (y/n)" thumbs
#echo "  Removing Empty Folders"
#mkdir -p "./00_Assets/_emptyFolders"
#touch ./00_Assets/_emptyFolders/.hidden
#find . -type d -empty -exec mv {} ./00_Assets/_emptyFolders/ &>/dev/null \;

if [[ -d "./02_Title" ]]; then
    echo "  Processing Titles"
    cd "./02_Title"
    for i in *; do
        if [[ -d "./$i" ]]; then
            cd "./$i"
            bash ${scriptPath}compressFolder "_AE"
            if [[ -d "./_Images" ]]; then
                echo "    Processing Stills for $i"
                cd "./_Images"
                bash ${scriptPath}processFilenames "$filePrefix"
                bash ${scriptPath}processPresets
                cd ..
            fi
            if [[ -d "./_Motions" ]]; then
                echo "    Processing Motions for $i"
                cd "./_Motions"
                if [[ "$thumbs" == "y" ]]; then
                    bash ${scriptPath}generateThumbs "_HD" "_" "_UW"
                    bash ${scriptPath}generateThumbs "_SD" "_UW"
                fi
                bash ${scriptPath}compressMOV
                bash ${scriptPath}processFilenames "$filePrefix"
                bash ${scriptPath}processPresets
                cd ..
            fi
            cd ..
        fi
    done
    cd ..
fi

if [[ -d "./03_Social" ]]; then
    echo "  Processing Socials"
    cd "./03_Social"
    bash ${scriptPath}renameSocials
    for i in *; do
        cd "./$i"
        bash ${scriptPath}compressFolder "_AE"
        if [[ -d "./_Images" ]]; then
            echo "    Processing Stills for $i"
            cd "./_Images"
            bash ${scriptPath}processFilenames "$filePrefix"
            bash ${scriptPath}processPresets
            cd ..
        fi
        if [[ -d "./_Motions" ]]; then
            echo "    Processing Motions"
            cd "./_Motions"
            if [[ "$thumbs" == "y" ]]; then 
                bash ${scriptPath}generateThumbs "_SQ"
            fi
            bash ${scriptPath}compressMOV "_CH_"
            bash ${scriptPath}processFilenames "$filePrefix"
            bash ${scriptPath}processPresets
            cd ..
        fi
        cd ..
    done
    cd ..
fi

if [[ -d "./04_Worship Background/_Motions" ]]; then
    echo "  Processing Worship Backgrounds"
    cd "./04_Worship Background/_Motions"
    if [[ "$thumbs" == "y" ]]; then 
        bash ${scriptPath}generateThumbs "_" "_" "_" "y"
    fi
    bash ${scriptPath}compressMOV
    bash ${scriptPath}processFilenames "$filePrefix"
    bash ${scriptPath}processPresets
    cd ../../
fi

if [[ -d "./05_Ultra Wide/_Motions" ]]; then
    echo "  Processing Ultra Wides"
    cd "./05_Ultra Wide/_Motions"
    if [[ "$thumbs" == "y" ]]; then 
        bash ${scriptPath}generateThumbs "_" "_" "_" "y"
    fi
    bash ${scriptPath}compressMOV
    bash ${scriptPath}processFilenames "$filePrefix"
    bash ${scriptPath}processPresets
    cd ../../
fi

if [[ -d "./06_Countdown/_Motions" ]]; then
    echo "  Processing Countdowns"
    cd "./06_Countdown/_Motions"
    if [[ "$thumbs" == "y" ]]; then
        bash ${scriptPath}generateThumbs "_HD"
        bash ${scriptPath}generateThumbs "_SD" "_UW"
    fi
    bash ${scriptPath}compressMOV
    bash ${scriptPath}processFilenames "$filePrefix"
    bash ${scriptPath}processPresets
    cd ../../
fi

if [[ -d "./07_Trivia/_Motions" ]]; then
    echo "  Processing Trivia"
    cd "./07_Trivia/_Motions"
    if [[ "$thumbs" == "y" ]]; then 
        bash ${scriptPath}generateThumbs "_HD" 
    fi
    bash ${scriptPath}compressMOV
    bash ${scriptPath}processFilenames "$filePrefix"
    bash ${scriptPath}processPresets
    cd ../../
fi

if [[ -d "./08_Bumper" ]]; then
    echo "  Processing Bumper"
    cd "./08_Bumper/_Motions"
    if [[ "$thumbs" == "y" ]]; then 
        bash ${scriptPath}generateThumbs "_HD"
    fi
    bash ${scriptPath}compressMOV    
    bash ${scriptPath}processFilenames "$filePrefix"
    bash ${scriptPath}processPresets
    cd ..
    bash ${scriptPath}compressFolder "_AE"
    cd ..
fi

if [[ -d "./09_PNGs" ]]; then
    echo "  Processing PNGs"
    if [[ -d "./Text PNGs" ]]; then
        cd "./Text PNGs"
        bash ${scriptPath}processFilenames "$filePrefix"
        hdpreset="#preset=tg_transparent_png_download_wide"
        sdpreset="#preset=tg_transparent_png_download_standard"
        jpgpreset="#preset=tg_transparent_png_preview"
        for i in *.jpg *.png; do
            # determine filetype
            if [[ "$i" == *".jpg"* ]]; then
                fileType=".jpg"
            elif [[ "$i" == *".png"* ]]; then
                fileType=".png"
            fi
            if [[ "$i" == *"_WIDE"* ]] && [[ "$i" == *"*.png"* ]]; then
                mv "$i" "${i%"$fileType"}${hdpreset}$fileType"
            elif [[ "$i" == *"_STD"* ]] && [[ "$i" == *"*.png"* ]]; then
                mv "$i" "${i%"$fileType"}${sdpreset}$fileType"
            elif [[ "$i" == *"*.jpg"* ]]; then
                mv "$i" "${i%"$fileType"}${jpgpreset}$fileType"
            fi
        done
        cd ..
    fi
    if [[ -d "./PNGs" ]]; then
        cd "./PNGs"
        bash ${scriptPath}processFilenames "$filePrefix"
        hdpreset="#preset=tg_transparent_png_download_wide"
        jpgpreset2="#preset=preview_only"
        for i in *.jpg *.png; do
            # determine filetype
            if [[ "$i" == *".jpg"* ]]; then
                fileType=".jpg"
            elif [[ "$i" == *".png"* ]]; then
                fileType=".png"
            fi
            if [[ "$i" == *"*.png"* ]]; then
                mv "$i" "${i%"$fileType"}${hdpreset}$fileType"
            elif [[ "$i" == *"*.jpg"* ]]; then
                mv "$i" "${i%"$fileType"}${jpgpreset2}$fileType"
            fi
        done
        cd ..
    fi
fi

echo
echo "Finished Processing Files for $filePrefix"
echo